apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: '{{ DEPLOY_APP }}'
  namespace: teamnks
  labels:
    team: teamnks
spec:
  image: '{{ image }}'
  replicas:
    min: 1
    max: 1
  liveness:
    path: /internal/isAlive
  readiness:
    path: /internal/isReady
  prometheus:
    enabled: true
    path: /internal/metrics
  observability:
    logging:
      destinations:
        - id: elastic
        - id: loki
  resources:
    limits:
      memory: 4096Mi
    requests:
      cpu: 5m
      memory: 256Mi
  accessPolicy:
    outbound:
      external:
        - host: test.salesforce.com
        - host: navdialog--preprod.my.salesforce.com
        - host: navdialog--uat.my.salesforce.com
  envFrom:
    - secret: kafka-nks
  kafka:
    pool: nav-dev # enum of nav-dev, nav-prod
  env:
    - name: KAFKA_TOPIC
      value: 'topic not specified'
    - name: MS_BETWEEN_WORK
      value: '600000'
    - name: KAFKA_POLL_DURATION
      value: '10000'
    - name: SF_TOKENHOST
      value: https://test.salesforce.com
    - name: KAFKA_CLIENT_ID
      value: '{{ DEPLOY_APP }}'
    - name: MESSAGE_ENCODING
      value: PLAIN # PLAIN, AVRO, AVRO_VALUE_ONLY
    - name: ENCODE_KEY
      value: 'false'
    - name: LIMIT_ON_DATES
      value: 'false'
    - name: DEPLOY_APP
      value: '{{ DEPLOY_APP }}'
    - name: DEPLOY_CLUSTER
      value: '{{ DEPLOY_CLUSTER }}'
    - name: FLAG_SEEK
      value: '{{ FLAG_SEEK }}'
    - name: SEEK_OFFSET # Only applied if flag SEEK is set (currently assuming one partition)
      value: '{{ SEEK_OFFSET }}'
    - name: NUMBER_OF_SAMPLES
      value: '{{ NUMBER_OF_SAMPLES }}'
    - name: FLAG_NO_POST
      value: '{{ FLAG_NO_POST }}'
    - name: FLAG_ALT_ID
      value: '{{ FLAG_ALT_ID }}'